### ISSUE TITLE
Support Plug-n-Play (yarn v2)

### ISSUE THREAD

**Issue by brandon-leapyear** [nestjs/graphql#1263]
## I'm submitting a...
<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
Running tests with yarn version 2 shows a bunch of errors like
```
The "apollo-server-express" package is missing. Please, make sure to install this library ($ npm install apollo-server-express) to take advantage of GraphQLModule.
```
Yarn version 2 started using the Plug-n-Play API, which prevents packages from `require`-ing dependencies not explicitly listed in the package's `package.json`. I'm not sure what the best solution is, but one solution is to add `apollo-server-express` as a peer dependency for `@nestjs/graphql`. This workaround works for me

```yaml
# .yarnrc.yml
packageExtensions:
  '@nestjs/graphql@*':
    peerDependencies:
      'apollo-server-express': '*'
      '@apollo/federation': '*'
```

Also see: https://github.com/nestjs/nest/issues/5836

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by PiDelport** [comment]
**@nestjs/graphql** is also missing peer dependencies for **class-transformer** and **class-validator** (requested by **@nestjs/mapped-types**)

```
➤ YN0002: │ @nestjs/graphql@npm:7.9.8 [59d7f] doesn't provide class-transformer (pbe5e2), requested by @nestjs/mapped-types
➤ YN0002: │ @nestjs/graphql@npm:7.9.8 [59d7f] doesn't provide class-validator (p7ca35), requested by @nestjs/mapped-types
```

Workaround:

```yaml
packageExtensions:
  '@nestjs/graphql@*':
    peerDependencies:
      class-transformer: '^0.3.2'
      class-validator: '^0.13.1'
```
